from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from artek_buddy.computer.capabilities import ComputerCapabilities
from artek_buddy.computer.client import SandboxBox
from artek_buddy.contracts.domain import Bot, ComputerStatus, ScreenUrlResult


@runtime_checkable
class ComputerGateway(Protocol):
    """Protocol for host-level computer service managing Team vs Private bot sandboxes."""

    capabilities: ComputerCapabilities

    def status(self, bot: Bot) -> ComputerStatus: ...
    def boot(self, bot: Bot) -> ComputerStatus: ...
    def stop(self, bot: Bot) -> ComputerStatus: ...
    def restart(self, bot: Bot) -> ComputerStatus: ...
    def reset(self, bot: Bot) -> ComputerStatus: ...
    def screen_url(self, bot: Bot) -> ScreenUrlResult: ...
    def execute(self, bot: Bot, command: str) -> dict[str, Any]: ...
    def health(self) -> bool: ...


@runtime_checkable
class SupervisorGateway(Protocol):
    """Protocol for loopback supervisor client interacting across the Docker socket boundary."""

    capabilities: ComputerCapabilities

    def provision(self, bot_id: str, home_key: str) -> SandboxBox: ...
    def inspect(self, provider_ref: str) -> SandboxBox: ...
    def stop(self, provider_ref: str) -> bool: ...
    def execute(self, provider_ref: str, command: str) -> dict[str, Any]: ...
    def act(self, provider_ref: str, actions: list[dict[str, Any]]) -> dict[str, Any]: ...
    def observe(self, provider_ref: str, include_image: bool = True) -> dict[str, Any]: ...
    def send_input(
        self, provider_ref: str, kind: str, payload: dict[str, Any]
    ) -> dict[str, Any]: ...
    def list_files(self, provider_ref: str, path: str = "/") -> dict[str, Any]: ...
    def write_file(self, provider_ref: str, path: str, content: str) -> dict[str, Any]: ...
    def health(self) -> bool: ...
