from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Procedure:
    name: str
    method: str
    path: str
    input_model: str | None
    output_model: str
    implemented: bool


def _p(
    name: str,
    method: str,
    path: str,
    input_model: str | None,
    output_model: str,
    implemented: bool = False,
) -> Procedure:
    return Procedure(
        name=name,
        method=method,
        path=path,
        input_model=input_model,
        output_model=output_model,
        implemented=implemented,
    )


# Reserved product surface under /v1/ plus live host routes.
PROCEDURES: list[Procedure] = [
    # Live host (implemented)
    _p("health", "GET", "/health", None, "HealthResponse", True),
    _p("models.list", "GET", "/v1/models", None, "ModelListResponse", True),
    _p("session.get", "GET", "/v1/session", None, "SessionResponse", True),
    _p("session.create", "POST", "/v1/session", "SessionRequest", "SessionResponse", True),
    _p("runs.create", "POST", "/v1/runs", "RunRequest", "Run", True),
    _p("devices.pairing", "POST", "/v1/devices/pairing", None, "PairingCode", True),
    _p("devices.create", "POST", "/v1/devices", "CreateDeviceInput", "DeviceCreated", True),
    _p("devices.list", "GET", "/v1/devices", None, "DeviceList", True),
    _p("devices.revoke", "DELETE", "/v1/devices/{device_id}", None, "Device", True),
    # Identity / deployment
    _p("me", "GET", "/v1/me", None, "Me", True),
    _p("deployment.get", "GET", "/v1/deployment", None, "DeploymentSettings", True),
    _p(
        "deployment.update",
        "PATCH",
        "/v1/deployment",
        "UpdateDeploymentInput",
        "DeploymentSettings",
        True,
    ),
    # Models (reserved extras)
    _p("models.credentials", "GET", "/v1/models/credentials", None, "ModelCredentialList"),
    _p("models.connect", "POST", "/v1/models/credentials", "ConnectModelInput", "ModelCredential"),
    _p(
        "models.begin_oauth",
        "POST",
        "/v1/models/oauth/begin",
        "BeginOAuthInput",
        "BeginOAuthResult",
    ),
    _p(
        "models.complete_oauth",
        "POST",
        "/v1/models/oauth/complete",
        "CompleteOAuthInput",
        "CompleteOAuthResult",
    ),
    _p("models.set_default", "POST", "/v1/models/default", "SetDefaultModelInput", "OkResponse"),
    # Bots
    _p("bots.list", "GET", "/v1/bots", None, "BotList", True),
    _p("bots.list_archived", "GET", "/v1/bots/archived", None, "BotList", True),
    _p("bots.get", "GET", "/v1/bots/{bot_id}", "BotIdInput", "Bot", True),
    _p("bots.create", "POST", "/v1/bots", "CreateBotInput", "Bot", True),
    _p("bots.duplicate", "POST", "/v1/bots/{bot_id}/duplicate", "BotIdInput", "Bot", True),
    _p("bots.update", "PATCH", "/v1/bots/{bot_id}", "UpdateBotInput", "Bot", True),
    _p("bots.set_computer", "POST", "/v1/bots/{bot_id}/computer", "SetComputerInput", "Bot", True),
    _p("bots.archive", "POST", "/v1/bots/{bot_id}/archive", "BotIdInput", "OkResponse", True),
    _p("bots.restore", "POST", "/v1/bots/{bot_id}/restore", "BotIdInput", "OkResponse", True),
    _p("bots.remove", "DELETE", "/v1/bots/{bot_id}", "DeleteBotInput", "OkResponse", True),
    # Threads
    _p("threads.get", "GET", "/v1/threads/{bot_id}", "BotIdInput", "ThreadSnapshot", True),
    _p(
        "threads.messages",
        "GET",
        "/v1/threads/{bot_id}/messages",
        "ThreadMessagesInput",
        "ThreadMessagePage",
        True,
    ),
    _p("messages.list", "GET", "/v1/messages", "ThreadMessagesInput", "ThreadMessagePage", True),
    _p(
        "threads.subscribe",
        "GET",
        "/v1/threads/{bot_id}/events",
        "ThreadSubscribeInput",
        "ProductEventStream",
        True,
    ),
    _p("workspace.subscribe", "GET", "/v1/events", None, "ProductEventStream", True),
    _p(
        "threads.send",
        "POST",
        "/v1/threads/{bot_id}/messages",
        "ThreadSendInput",
        "ThreadSendResult",
        True,
    ),
    _p(
        "threads.attachments",
        "POST",
        "/v1/threads/{bot_id}/attachments",
        "AttachmentUploadInput",
        "AttachmentList",
        True,
    ),
    _p("threads.stop", "POST", "/v1/threads/{bot_id}/stop", "BotIdInput", "OkResponse", True),
    _p(
        "threads.follow_up",
        "POST",
        "/v1/threads/{bot_id}/follow-up",
        "ThreadFollowUpInput",
        "OkResponse",
        True,
    ),
    _p("threads.answer", "POST", "/v1/threads/{bot_id}/answer", "ThreadAnswerInput", "OkResponse"),
    _p(
        "consents.answer",
        "POST",
        "/v1/consents/{consent_id}",
        "ConsentAnswerInput",
        "OkResponse",
        True,
    ),
    _p("consents.get", "GET", "/v1/consents/{consent_id}", None, "ConsentJob", True),
    _p(
        "consents.file",
        "POST",
        "/v1/consents/{consent_id}/file",
        "ConsentFileInput",
        "OkResponse",
        True,
    ),
    _p(
        "consents.result",
        "POST",
        "/v1/consents/{consent_id}/result",
        "ConsentResultInput",
        "OkResponse",
        True,
    ),
    _p("threads.mark_read", "POST", "/v1/threads/{bot_id}/read", "BotIdInput", "OkResponse", True),
    _p(
        "threads.mark_unread",
        "POST",
        "/v1/threads/{bot_id}/unread",
        "BotIdInput",
        "OkResponse",
        True,
    ),
    _p("subagents.list", "GET", "/v1/bots/{bot_id}/subagents", "BotIdInput", "SubagentList", True),
    _p(
        "subagents.stop",
        "POST",
        "/v1/bots/{bot_id}/subagents/{subagent_id}/stop",
        None,
        "Subagent",
        True,
    ),
    _p(
        "subagents.restart",
        "POST",
        "/v1/bots/{bot_id}/subagents/{subagent_id}/restart",
        None,
        "Subagent",
        True,
    ),
    _p(
        "subagents.steer",
        "POST",
        "/v1/bots/{bot_id}/subagents/{subagent_id}/steer",
        "SteerSubagentInput",
        "Subagent",
        True,
    ),
    # Computer
    _p("computer.status", "GET", "/v1/computer/{bot_id}", "BotIdInput", "ComputerStatus", True),
    _p("computer.boot", "POST", "/v1/computer/{bot_id}/boot", "BotIdInput", "ComputerStatus", True),
    _p("computer.stop", "POST", "/v1/computer/{bot_id}/stop", "BotIdInput", "ComputerStatus", True),
    _p(
        "computer.restart",
        "POST",
        "/v1/computer/{bot_id}/restart",
        "BotIdInput",
        "ComputerStatus",
        True,
    ),
    _p(
        "computer.reset",
        "POST",
        "/v1/computer/{bot_id}/reset",
        "BotIdInput",
        "ComputerStatus",
        True,
    ),
    _p(
        "computer.takeover",
        "POST",
        "/v1/computer/{bot_id}/takeover",
        "BotIdInput",
        "TakeoverResult",
        True,
    ),
    _p(
        "computer.release",
        "POST",
        "/v1/computer/{bot_id}/release",
        "BotIdInput",
        "OkResponse",
        True,
    ),
    _p(
        "computer.input", "POST", "/v1/computer/{bot_id}/input", "ComputerInput", "OkResponse", True
    ),
    _p(
        "computer.files",
        "GET",
        "/v1/computer/{bot_id}/files",
        "ComputerFilesInput",
        "ComputerFileList",
        True,
    ),
    _p(
        "computer.read_file",
        "GET",
        "/v1/computer/{bot_id}/files/read",
        "ComputerReadFileInput",
        "ComputerFileContent",
        True,
    ),
    _p(
        "computer.download_file",
        "GET",
        "/v1/computer/{bot_id}/files/raw",
        "ComputerReadFileInput",
        "File",
        True,
    ),
    _p(
        "computer.screen_url",
        "GET",
        "/v1/computer/{bot_id}/screen",
        "BotIdInput",
        "ScreenUrlResult",
        True,
    ),
    _p(
        "computer.heartbeat",
        "POST",
        "/v1/computer/{bot_id}/heartbeat",
        "BotIdInput",
        "OkResponse",
        True,
    ),
    # Memory
    _p("memory.list", "GET", "/v1/memory", "MemoryListInput", "MemoryDocumentList", True),
    _p("memory.create", "POST", "/v1/memory", "CreateMemoryInput", "MemoryDocument", True),
    _p(
        "memory.update",
        "PATCH",
        "/v1/memory/{document_id}",
        "MemoryUpdateInput",
        "MemoryDocument",
        True,
    ),
    _p("memory.remove", "DELETE", "/v1/memory/{document_id}", None, "OkResponse", True),
    _p(
        "memory.export_markdown",
        "GET",
        "/v1/memory/export",
        "MemoryExportInput",
        "MarkdownExport",
        True,
    ),
    # Routines
    _p("routines.list", "GET", "/v1/routines", "BotIdInput", "RoutineList", True),
    _p("routines.create", "POST", "/v1/routines", "CreateRoutineInput", "Routine", True),
    _p(
        "routines.update",
        "PATCH",
        "/v1/routines/{routine_id}",
        "UpdateRoutineInput",
        "Routine",
        True,
    ),
    _p(
        "routines.remove",
        "DELETE",
        "/v1/routines/{routine_id}",
        "RoutineIdInput",
        "OkResponse",
        True,
    ),
    _p(
        "routines.test_run",
        "POST",
        "/v1/routines/{routine_id}/test",
        "RoutineIdInput",
        "TestRunResult",
        True,
    ),
    # Capabilities / connections
    _p("capabilities.list", "GET", "/v1/capabilities", None, "CapabilityInstallList"),
    _p(
        "capabilities.install",
        "POST",
        "/v1/capabilities",
        "InstallCapabilityInput",
        "CapabilityInstall",
    ),
    _p("capabilities.remove", "DELETE", "/v1/capabilities/{id}", "CapabilityIdInput", "OkResponse"),
    _p(
        "connections.catalog",
        "GET",
        "/v1/connections/catalog",
        "ConnectionCatalogInput",
        "ConnectionCatalog",
    ),
    _p("connections.list", "GET", "/v1/connections", None, "ConnectionList"),
    _p(
        "connections.begin",
        "POST",
        "/v1/connections",
        "BeginConnectionInput",
        "BeginConnectionResult",
    ),
    _p(
        "connections.complete",
        "POST",
        "/v1/connections/{connection_id}/complete",
        "CompleteConnectionInput",
        "Connection",
    ),
    _p(
        "connections.revoke",
        "POST",
        "/v1/connections/{connection_id}/revoke",
        "ConnectionIdInput",
        "OkResponse",
    ),
    # Artifacts / usage / export / notifications
    _p("artifacts.list", "GET", "/v1/artifacts", "BotIdInput", "ArtifactList", True),
    _p("artifacts.download", "GET", "/v1/artifacts/{artifact_id}", None, "File", True),
    _p("usage.list", "GET", "/v1/usage", None, "UsageRecordList"),
    _p("usage.summary", "GET", "/v1/usage/summary", None, "UsageSummary"),
    _p("export.bot", "GET", "/v1/export/{bot_id}", "BotIdInput", "ExportManifest"),
    _p(
        "notifications.register_push",
        "POST",
        "/v1/notifications/push",
        "RegisterPushInput",
        "OkResponse",
    ),
]

PROCEDURES_BY_NAME: dict[str, Procedure] = {item.name: item for item in PROCEDURES}
